### ISSUE TITLE
Twilio Credentials in .zshrc.local

### ISSUE THREAD

**Issue by mlocher** [hogihung/dotfilez#1]
Hey John, 

first, thanks for applying for a position at Codeship :smile: (I'll get back to you regarding this later)

The real reason why I'm getting in touch (via a GitHub issue) is that the `.zshrc.local` file in this repository contains Twilio credentials that you probably want to remove (and reset).

See https://github.com/hogihung/dotfilez/blob/master/.zshrc.local#L56-L57

**Comment by hogihung** [comment]
Thank you.

**Comment by hogihung** [comment]
Oh, thank you.  That is demo stuff that definitely should not have been checked in.  Very much appreciate the heads up.

John..
